Mentoring-t-66 로또 프로그램 구현 과제 제출
BI-kotlin-in-action/Juyeol-Song-Project-Hw pull request #1
Opened 2023-11-07 04:03 UTC by Unagi-zoso

선택사항

1. 모든 validation을 세세하게 지정해본다.
3. 각 코드의 역할과 도메인에 따라 파일 혹은 패키지를 분리해본다.
4. 수동 로또와 자동 로또를 생성하는 로직을 전략 패턴으로 구현해본다.

잘 부탁드리겠습니다!

2023-11-07 12:44 UTC, konempty commented
헉 ㅋㅋㅋㅋ 불필요한 파일들이 너무 많이 보이는데 
깃 이그노어로 불필요한 파일들은 깃헙에 올라오지 않도록 처리해주세요~!
https://www.toptal.com/developers/gitignore/
저는 주로 여기를 사용하는데 자신이 프로젝트에 사용하는 기술 스택을 넣으면
적절한 깃이그노어 파일을 생성해줘요!

2023-11-07 13:11 UTC, konempty requested changes
크 많은 노력을 하신게 코드에서 느껴지네요 ㅋㅋㅋ
그리고 선택사항도 꽤 준수하게 구현하셨구요
조금만더 수정 부탁드릴게요~!

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/MainApplication.kt
> +    user.showEarnedMoney()
요 프로젝트에서 나눌만한 3가지 패키지을 알려드릴게요!

1. 도메인 : 단순히 정보를 가지고 패키지 간의 정보 전달을 위해 사용되는 클래스 모음
2. 뷰 : IO에 관련된 모든 로직을 수행하는 클래스 모음
3. 컨트롤러 : 뷰와 도메인을 받아들여 프로그램의 전체과정을 컨트롤하는 역할

여기에서 user클래스는 이름만 봤을때는 도메인의 역할이 어울려 보이는데
실제 하는 역할은 뷰, 컨트롤러, 도메인의 모든 역할을 수행하고 있어서 
너무 바빠보이는 클래스네요 ㅋㅋㅋ

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lotto/Lotto.kt
> +        print("$prefix${numbers.sorted().joinToString()}$postfix")
요건 도메인 객체가 할 일이 아니라 View에서 처리해야할것 같아요~!

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lotto/Lotto.kt
> +        generateStrategy(this, numOfLottos)
로또를 넘겨서 숫자를 각각 채우는게 아니라
숫자 6개를 한번에 받아서 로또를 생성하는게 더 자연스러울것 같아요!

(로또 숫자 한개)라는 도메인과 (로또 종이 한장)이라는 도메인중 누가 더 큰지 고민해보시구요
작은쪽이 큰쪽에게 전달되는게 더 자연스럽다 라고 알고계시면 될것 같아요!

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lottomachine/AutomaticLottoMachineStrategy.kt
> +        get() = 1000
크 요런 상수화 좋습니다
다만 프로그램 전역적에서 변하지 않는 값이니
static화를 시켜준다면 더 좋을것 같아요!

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lottomachine/AutomaticLottoMachineStrategy.kt
> +                lotto.numbers.add(Random.nextInt(1, 46))
요건 코멘트는 아니고 단순 제안인데
중복 없이 숫자를 뽑는 로직은 셔플링과 subList를 사용하는거예요!
ex)
1, 2, 3, 4, 5, 6의 숫자 배열에서 중복없이 3개를 뽑으려면
셔플링 후(2, 6, 3, 4, 5, 1)
앞에서 부터 3개 추출 (2, 6, 3)

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lottomachine/LottoMachineStrategy.kt
> +    val COST_OF_ONE_LOTTO: Int
자동 로또/ 수동 로또 여부에 따라 요 값이 변하지 않을것 같은데
요렇게 선언하신 이유가 있으실까요??

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lottomachine/LottoMachineStrategy.kt
> +    fun drawLottos(user: User, numOfLottos: Int = 0): List<Lotto> {
draw? 라는 동사는 뭔가 어색하네요 ㅋㅋ..
혹시 영어로는 로또를 그리다? 라고 표현하나요??

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lottomachine/ManualLottoMachineStrategy.kt
> +        var inputNumbers = setOf<Int>()
굳이 초기화를 해주신 이유가 있을까요??

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lotto/Lotto.kt
> +class Lotto(numOfLottos: Int = 6, generateStrategy: (lotto: Lotto, numOfLottos: Int) -> Unit) {
numOfLottos는 전역적으로 변치않는 값을것 같은데 상수화를 하고
사용하는 곳에서 해당 상수를 가져오는 방식이 더 어울릴것 같은데
람다에 파라메터로 넘겨주는 이유가 있을까요??

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lottomachine/ManualLottoMachineStrategy.kt
> +        if (inputNumber.any { it !in 1..45 }) {
로또 숫자의 최솟값과 최대값도 상수화를 하거나 도메인화 시킬수 있지 않을까요??

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lottomachine/ManualLottoMachineStrategy.kt
> +        if (inputNumber.size == numOfSelection && inputNumber.all { it in 1..45 }) {
위에서 했던 비교를 다시 반복하는데 좀더 효율적으로 처리할수 있지 않을까요??

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/user/User.kt
> +            break
요 코드느는 재활용이 될것 같지 않은 코드인데 init블럭 내부에서 구현하는게 아닌
별도의 함수로 빼낸건 좀더 예뻐보이기 위함일까요?

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/user/User.kt
> +        lottos = lottos + AutomaticLottoMachineStrategy().drawLottos(this, maxNumOfLottos - numOfManual)
ㄷㄷㄷㄷ 요 메소드 내부에서 
AutomaticLottoMachineStrategy와 ManualLottoMachineStrategy의 객체는 몇개나 생성되고
바로 버려지는건가요 ㅋㅋㅋ

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/user/User.kt
> +            println("${index + 1} : " + lotto.numbers.sorted().joinToString(" "))
역시 여기서 결국 sorted를 호출하게 되는군요 ㅎㅎ...
만약 처음부터 numvers가 sortedSet이었다면 어떨까요??

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/winninglotto/WinningLotto.kt
> +        return winningLotto.numbers.intersect(otherLotto.numbers)
어떤 원소가 교집합인지는 관심대상이 아닐것 같구요 
교집합 원소의 개수만 알아도 충분하지 않을까요??
return winningLotto.numbers.intersect(otherLotto.numbers).count

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/winninglotto/WinningLotto.kt
> +            else -> NOPE
몇개 맞았을때 어떤 enum값이 반환될지는 WinningPrize의 책임/역할일것 같아요!
따라서 
```kotlin
return WinningPrize.getPrize(matchedNumbers.size)
```
요렇게 할수 있도록 하면 좋을것 같아요!

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/winninglotto/WinningLotto.kt
> +        print("당첨 번호 : ${matchedNumbers.sorted().joinToString(" ")}  ")
아 ㅋㅋㅋ 여기서 어떤 원소가 맞았는지 노출해주는군요
요건 쪼금 과하지 않나 싶긴 한데 요런 의도라면 getMatchedNumberSet가 Set을 반환하는것도 
괜찮을것 같네요

2023-11-07 13:11 UTC, konempty commented on lotto-project/src/main/kotlin/lottomachine/LottoMachineStrategy.kt
> +        return currentMoney / COST_OF_ONE_LOTTO
요걸 계산하는건 로또 생성기의 책임일지는 조금 의문이 드네요 ㅋㅋㅋ

2023-11-07 15:44 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/lotto/Lotto.kt
> +        generateStrategy(this, numOfLottos)
사실 작성하면서 위화감을 많이 느낀 방식이네요. 말씀해주신 부분은 정말 와닿는 비유 같아요. 최대한 제 코드에 잘 녹여볼게요. 감사합니다

2023-11-08 10:56 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/lottomachine/AutomaticLottoMachineStrategy.kt
> +                lotto.numbers.add(Random.nextInt(1, 46))
이런 방식도 있군요. 잘 적용해보겠습니다. 감사합니다.

2023-11-08 11:00 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/lottomachine/LottoMachineStrategy.kt
> +    val COST_OF_ONE_LOTTO: Int
인터페이스에 대한 이해가 부족했던 것 같습니다! 인터페이스 내에서 정적으로 접근할 수 있게 바꿔보겠습니다!
감사합니다!

2023-11-08 11:01 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/lottomachine/LottoMachineStrategy.kt
> +    fun drawLottos(user: User, numOfLottos: Int = 0): List<Lotto> {
카드를 뽑을 때 draw라는 동사를 썼던 걸로 알아서 한 번 써봤는데 좀 더 일반적인 동사로 바꾸는 게 좋아보이네요!
감사합니다!

2023-11-08 11:27 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/lottomachine/ManualLottoMachineStrategy.kt
> +        var inputNumbers = setOf<Int>()
예전에 공부할 때 변수 선언할 때는 초기화를 꼭하라는 말이 있어서 의식했던 것 같습니다.
흐름상 문제 없다면 late하게 초기화를 해도 괜찮을까요?

2023-11-08 11:27 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/lotto/Lotto.kt
> +class Lotto(numOfLottos: Int = 6, generateStrategy: (lotto: Lotto, numOfLottos: Int) -> Unit) {
그게 더 깔끔할 것 같네요. 감사합니다!

2023-11-08 11:36 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/lottomachine/ManualLottoMachineStrategy.kt
> +        if (inputNumber.any { it !in 1..45 }) {
와.... 감사합니다!

2023-11-08 11:54 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/lottomachine/ManualLottoMachineStrategy.kt
> +        if (inputNumber.size == numOfSelection && inputNumber.all { it in 1..45 }) {
감사합니다!

2023-11-08 12:00 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/user/User.kt
> +        lottos = lottos + AutomaticLottoMachineStrategy().drawLottos(this, maxNumOfLottos - numOfManual)
혹시 전략 패턴의 구현체를 싱글톤으로 만들어도 괜찮을까요? 구현체의 내부값을 변경시키지 않고 다른 클래스에서 자주 접근하네요.

2023-11-08 12:02 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/user/User.kt
> +            break
네. 시작 금액을 초기화하며 유효성 검사를 하는 역할도 있어서 따로 함수로 만들었습니다.

2023-11-08 12:03 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/user/User.kt
> +            println("${index + 1} : " + lotto.numbers.sorted().joinToString(" "))
지당하십니다!

2023-11-08 13:03 UTC, konempty commented
ㅠㅠ 코드를 보기 힘드네요 깃 이그노어 처리를 부탁드릴게요
깃이그노어 처리하고 이미 올라간 파일들을 지워주는 작업까지 해야 하는데 아래 링크를 참고해주세요
https://devjeonblog.oopy.io/3d13207f-b830-4bbc-9d35-bd6dbfc824f0

2023-11-08 13:11 UTC, Unagi-zoso commented
프로젝트를 하며 궁금한 것이 생겼는데 혹시 괜찮다면 의견을 들을 수 있을까요?

1. 만약 자동차와 사람 도메인 간에 ride라는 행위를 정의할 때,
자동차와 사람이 있을 때 자동차를 탄다는 행위는 
사람이 자동차를 탄다는 행위로 사람에게 ride(car: Car) 메서드를 정의해야할까요? 
아니면 자동차가 사람을 태우는 것이니 자동차에게 ride(human: Human) 메서드를 정의해야할까요?

2. 프로젝트 중 책임 별로 Domain, View, Controller로 분리하여 클래스를 작성하였습니다. 
혹시 패키지로 책임에 따라 메서드를 분리해놓고 확장함수로 도메인에 함수를 추가하면 
책임을 분리했다고 보기는 어렵나요?

3. 저는 추가사항으로 전략 패턴을 사용해 로또 생성 시 선택할 수 있게 하였습니다. 
전략 구현체의 기능 중엔 전략 구현 객체의 필드를 새로 write를 한다 같은 경우는 없어(safe) 싱글톤으로 구현체들을 생성하였습니다. 
또한 객체 생성 때 마다 사용될테니 사용빈도도 높다 생각하여 singleton으로 생성하는 것이 좀 더 낭비를 막을 수 있지 않을까 생각하였습니다. 이게 괜찮은 방식일까요?

2023-11-08 13:34 UTC, konempty requested changes
크 코드가 확실히 많이 개선이 되었네요
그래도 쪼금만더 수정 부탁드릴게요!

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/MainApplication.kt
> +    val winningLottoController = WinningLottoController()
앗.. 제 설명이 부족 했군요
프로그램을 컨트롤하는 컨트롤러는 보통 한개만 만들어서 해당 컨트롤러가 프로그램의 모든 로직을 다뤄야해요

좋은 예시중에 하나를 보여드리자면 아래 인규님 프로젝트에서 잘 드러납니다!
https://github.com/BI-kotlin-in-action/InGyuMoon-lotto/blob/a73f5bf3ed67a3974a66d6baf2c1f22931b047aa/src/main/kotlin/Main.kt

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/MainApplication.kt
> +    val lottoView = LottoView()
뷰또한 컨트롤러 내부에서 사용되어야 해요

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/controller/lotto/LottoController.kt
> +        user.lottos += AutomaticLottoMachineStrategy.makeLottos(user.maxNumOfLottos - numOfManuals)
요건 전략 패턴 보다는 팩토리 패턴에 가까운것 같아요..!
val manualLotto = LottoGenerator(ManualLottoMachineStrategy::makeLottos)
val autoLotto = LottoGenerator(AutomaticLottoMachineStrategy::makeLottos)
요런 느낌으로 전략을 넘겨주고 해당 전략에 의해 한개의 객체가 수행해내는 과정이 달라지는걸 의미해요

반대로 팩토리 패턴은
한개의 메소드(팩토리 메소드)에 필요한 모든 파라메터를 넘겨주고 해당 팩토리 메소드가 생성해내는 결과가
팩토리를 바꿈에 따라 달라지는걸 의미해요

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/domain/lotto/Lotto.kt
> +    val numbers = generateStrategy()
오 요부분은 조금 전략패턴의 느낌이 살아있네요!

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/domain/lottomachine/LottoMachineStrategy.kt
> +        return List(numOfLottos) { Lotto(generateStrategy = { generateLotto() }) }
오호... 코드의 느낌이 이상한데
팩토리 패턴 내부에서 전략패턴을 쓰는 듯한 느낌이라 순수한 전략패턴이 아닌것 같아서 아쉽네요 ㅠㅠ

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/domain/lottomachine/AutomaticLottoMachineStrategy.kt
> +    private val numberOneToFortyFive = (MIN_LOTTO_NUMBER..MAX_LOTTO_NUMBER)
요건 프로그램 전역적으로 유니크해도 좋을것 같은데 static으로 처리해도 괜찮지 않을까요??

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/domain/lottomachine/LottoMachineStrategy.kt
> + * 전략 패턴 인터페이스와 구현체는 domain 패키지에 분류하여도 괜찮을까요?
으흠 유틸클래스의 느낌이 강하니까 util이라는 별도의 패키지로 빼내는게 좋을것 같아요!
꼭 제가 제시한 3개의 패키지에만 얽매일 필요는 없어요 ㅎㅎ

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/domain/lottomachine/LottoMachineStrategy.kt
> +            get() = 1000
val COST_OF_ONE_LOTTO: Int = 1000
이 아니라 getter를 정의한 이유가 궁금합니다!

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/domain/user/User.kt
> +    var lottos: List<Lotto> = listOf(),
요건 val이어도 괜찮지 않을까요??
혹시 요 값을 바꾸는 코드가 있을까요?

2023-11-08 13:34 UTC, konempty commented on lotto-project/src/main/kotlin/domain/winninglotto/WinningLotto.kt
> +    val winningLotto = Lotto(generateStrategy = { AutomaticLottoMachineStrategy.generateLotto() })
오 요기도 전략 패턴의 느낌이 드네요 ㅋㅋㅋ
좀더 수정 하자면 
`val winningLotto = Lotto(AutomaticLottoMachineStrategy::generateLotto)`
요렇게 하면 완전하게 람다를 사용하는것 같아서 좋을것 같아요!

2023-11-08 13:39 UTC, konempty commented
> 만약 자동차와 사람 도메인 간에 ride라는 행위를 정의할 때,
> 자동차와 사람이 있을 때 자동차를 탄다는 행위는
> 사람이 자동차를 탄다는 행위로 사람에게 ride(car: Car) 메서드를 정의해야할까요?
> 아니면 자동차가 사람을 태우는 것이니 자동차에게 ride(human: Human) 메서드를 정의해야할까요?

=> 케바케일것 같아요 ㅋㅋㅋ
프로그램 상에서 누가 더 중요한 도메인이냐에 따라 행동주체가 달라질것 같아요
하지만 저는 주로 인지 부하를 낮추기 위해서 차에 사람이 탄다 
즉, 차가 행동 주체가 되는걸 선호할것 같아요!

> 프로젝트 중 책임 별로 Domain, View, Controller로 분리하여 클래스를 작성하였습니다.
> 혹시 패키지로 책임에 따라 메서드를 분리해놓고 확장함수로 도메인에 함수를 추가하면
> 책임을 분리했다고 보기는 어렵나요?
=> 확장함수로 도메인에 함수를 추가하는 케이스가 잘 안떠오르는데 굳이 멤버 메소드가 아니라 확장함수로 정의하는 이유가 뭘지 궁금하네요!

> 저는 추가사항으로 전략 패턴을 사용해 로또 생성 시 선택할 수 있게 하였습니다.
> 전략 구현체의 기능 중엔 전략 구현 객체의 필드를 새로 write를 한다 같은 경우는 없어(safe) 싱글톤으로 구현체들을 생성하였습니다.
> 또한 객체 생성 때 마다 사용될테니 사용빈도도 높다 생각하여 singleton으로 생성하는 것이 좀 더 낭비를 막을 수 있지 않을까 생각하였습니다. 이게 괜찮은 방식일까요?

=> 그런 의도라면 싱글톤 보다 더 가볍게 static 메소드 들로만 구현하면 좋을것 같아요!

2023-11-08 13:44 UTC, Unagi-zoso commented
> => 확장함수로 도메인에 함수를 추가하는 케이스가 잘 안떠오르는데 굳이 멤버 메소드가 아니라 확장함수로 정의하는 이유가 뭘지 궁금하네요!

제가 컨트롤러의 역할을 각 도메인들이 하는 행위(메소드)를 정의하는 클래스라고 오해해서 그런거 같아요. 대부분 멤버 메소드로 구현하면 될 거 같아요. 감사합니다!

2023-11-08 13:45 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/MainApplication.kt
> +    val winningLottoController = WinningLottoController()
제 배움이 부족했습니다! 감사합니다!

2023-11-08 13:59 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/domain/lottomachine/LottoMachineStrategy.kt
> + * 전략 패턴 인터페이스와 구현체는 domain 패키지에 분류하여도 괜찮을까요?
감사합니다!

2023-11-08 14:07 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/domain/lottomachine/LottoMachineStrategy.kt
> +            get() = 1000
처음에 interface에 직접 변수를 선언하고 이 때  getter 접근 시 값을 반환하도록 적었습니다. 그 부분을 companion object로 두면서 그대로 따라 넣었습니다.  getter 정의 말고 직접 값을 넣겠습니다!

2023-11-08 14:14 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/domain/user/User.kt
> +    var lottos: List<Lotto> = listOf(),
currentMoney는 로또를 살 때 잔돈을 남기게 됩니다.
earnedMoney에서는 로또를 통해서 번 돈을 저장합니다.

lottos의 경우, manual로또와 auto로또로부터 전달 받을 시 기존에 있던 lottos와 LottoMachineStrategy 구현체가 만들어낸 lottos가 합쳐져서 다시  할당됩니다.  그래서 var로 선언하였습니다. 혹시 더 좋은 방법이 있을까요?

2023-11-08 14:15 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/domain/lottomachine/LottoMachineStrategy.kt
> + * 전략 패턴 인터페이스와 구현체는 domain 패키지에 분류하여도 괜찮을까요?
감사합니다! MVC 패턴에 대해서도 더 공부해보겠습니다!

2023-11-09 04:03 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/domain/lottomachine/LottoMachineStrategy.kt
> +        return List(numOfLottos) { Lotto(generateStrategy = { generateLotto() }) }
감사합니다. 최대한 개선해볼게요.

2023-11-09 04:04 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/controller/lotto/LottoController.kt
> +        user.lottos += AutomaticLottoMachineStrategy.makeLottos(user.maxNumOfLottos - numOfManuals)
그렇군요. 알려주신 부분을 최대한 반영해보겠습니다!

2023-11-09 04:52 UTC, konempty requested changes
크 거의 다온것 같아요!!
진짜 조금만더 수정 부탁드릴게요!

2023-11-09 04:52 UTC, konempty commented on lotto-project/src/main/kotlin/domain/lotto/Lotto.kt
> +data class Lotto(val numbers: SortedSet<Int>) {
참고로 일급컬렉션을 제대로 쓰려면 컬렉션을 외부로 부터 숨겨야하는게 맞아요..!
하지만 이미 요걸 사용하고 있는 코드가 많아서 수정이 어렵다면 그대로 두셔도 됩니다

2023-11-09 04:52 UTC, konempty commented on lotto-project/src/main/kotlin/domain/winninglotto/WinningLotto.kt
> +        return (winningLotto.numbers intersect otherLotto.numbers).toSortedSet()
ㅋㅋㅋㅋ DSL을 쓸거라곤 예상치 못했는데 너무 좋습니다 💯

2023-11-09 04:52 UTC, konempty commented on lotto-project/src/main/kotlin/domain/winninglotto/WinningPrize.kt
> +        fun convertToPrizeList(matchedNumbersList: List<SortedSet<Int>>): List<WinningPrize> {
으흠 요건 좀 고민되는데 SortedSet을 받아 들이는건 좀 불필요한 정보까지 넘어오는것 같은데
set의 사이즈만 추출해내서 사이즈 리스트를 넘겨주는게 좋을것 같구요
그게 어렵다면 가변성 노출을 최소화 하기 위해 List<Set<Int>>가 좋을것 같아요!

2023-11-09 04:52 UTC, konempty commented on lotto-project/src/main/kotlin/utils/lottomachine/ManualLottoMachineStrategy.kt
> +        private val manualLottoMachineView = ManualLottoMachineView()
으흠 유틸 클래스가 뷰를 소유하는건 좀 어색하네요 ㅎㅎ..
현실로 치면 몽키스패너에 키보드를 달아둔 느낌이랄까요..? ㅋㅋㅋ

2023-11-09 04:52 UTC, konempty commented on lotto-project/.gitignore
> +Lotto.iml
<img width="239" alt="스크린샷 2023-11-09 오후 1 48 18" src="https://github.com/BI-kotlin-in-action/Juyeol-Song-Project-Hw/assets/44064530/283e354f-60fc-4ea8-89d7-412c3de54551">


파일끝에 개행이 없다면 깃헙에서도 경고를 띄워주고
파일끝 개행은 일부 시스템에서는 없으면 에러를 일으킵니다..!
아래 URL을 확인해서 적용해주세요!

https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2023-11-09 04:52 UTC, konempty commented on lotto-project/src/main/kotlin/controller/lotto/LottoController.kt
> +    private val winningLottoView = WinningLottoView()
요 프로퍼티 들은 start메소드 내부에서 선언해도 괜찮지 않을까요??

2023-11-09 04:52 UTC, konempty commented on lotto-project/src/main/kotlin/domain/user/User.kt
> +    fun buyManualAndAutonomousLottos(numOfManuals: Int) {
외부의 로또기계(?)가 로또를 생성해서 유저에게 전달해주는게 좀더 자연스러울것 같아요..!
유저가 직접 로또를 생성한다는건 뭔가 어색하네요 ㅋㅋㅋ

2023-11-09 06:55 UTC, Unagi-zoso commented on lotto-project/.gitignore
> +Lotto.iml
주의하겠습니다! Ktlint에게 너무 의존해서 의식을 안했네요! 감사합니다!

2023-11-09 09:33 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/utils/lottomachine/ManualLottoMachineStrategy.kt
> +        private val manualLottoMachineView = ManualLottoMachineView()
몽키스패너 떼어 내겠습니다!

2023-11-09 09:35 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/domain/winninglotto/WinningPrize.kt
> +        fun convertToPrizeList(matchedNumbersList: List<SortedSet<Int>>): List<WinningPrize> {
평소에도 인스턴스의 필드 정보만 보내도 되는걸 인스턴스 자체를 넘기도록 자주 만들었었는데 잘 짚어주신거 같아요!
감사합니다

2023-11-09 09:35 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/domain/lotto/Lotto.kt
> +data class Lotto(val numbers: SortedSet<Int>) {
한 번 적용해 보겠습니다!

2023-11-09 09:37 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/domain/user/User.kt
> +    fun buyManualAndAutonomousLottos(numOfManuals: Int) {
로또 생성 책임을 지닌 객체에게 로또를 생성해서 전달하도록 만들어보겠습니다!

2023-11-09 10:19 UTC, konempty approved these changes
크 정말 고생 많으셨어요 ㅋㅋㅋㅋ
제가 중간에 리뷰를 잘못 드린것도 있구 고통이 눈으로 보이네요
요번 코멘트만 반영하고 머지해도 좋을듯 합니다~!

2023-11-09 10:19 UTC, konempty commented on lotto-project/src/main/kotlin/utils/lottomachine/ManualLottoMachineStrategy.kt
> +        private val manualLottoMachineView = ManualLottoMachineView()
헐 ㅠㅠㅠ 죄송해요 코드를 잘못 읽었네요
전략 패턴이라면 뷰가 전략안에 들어 있는게 맞아요

오히려 지금처럼 외부에서 주입 받는게 더 이상하네요

2023-11-09 10:19 UTC, konempty commented on lotto-project/src/main/kotlin/domain/winninglotto/WinningPrize.kt
> +                3 -> FOURTH
몇개 맞췄을때 어떤 값을 반환하는지 enum이 알고 있다면 코드를 더 간단하게 줄일수 있을것 같아요!
```kotlin
WinningPrize(val level: String, val matchCount:Int, val prizeAmount: Int)

FIRST("1등", 6, 100_000),
SECOND("2등", 5, 5_000),
... 중략

fun getPrize(numOfMatchedNumbers: Int): WinningPrize = 
        WinningPrize.values().find{it.matchCount == numOfMatchedNumbers} ?: NOPE
```

2023-11-09 10:19 UTC, konempty commented on lotto-project/src/main/kotlin/utils/lottomachine/AutomaticLottoMachineStrategy.kt
> +        private val numberOneToFortyFive = (MIN_LOTTO_NUMBER..MAX_LOTTO_NUMBER)
\@JvmStatic을 붙혀야 자바의 static에 대응이 됩니다~!

2023-11-09 10:24 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/domain/winninglotto/WinningPrize.kt
> +                3 -> FOURTH
아하 그렇네요! 감사합니다!

2023-11-09 10:24 UTC, Unagi-zoso commented on lotto-project/src/main/kotlin/utils/lottomachine/AutomaticLottoMachineStrategy.kt
> +        private val numberOneToFortyFive = (MIN_LOTTO_NUMBER..MAX_LOTTO_NUMBER)
감사합니다!

2023-11-09 13:04 UTC, merged