Mentoring-t-88 로또 웹 서비스 과제 제출하겠습니다.
BI-kotlin-in-action/Juyeol-Song-Project-Hw pull request #2
Opened 2023-11-30 03:29 UTC by Unagi-zoso

너무 늦게 올려 죄송합니다.

필수 요구사항 최대한 반영하였고 
선택 요구사항은 MySQL 사용, 회원가입, 로그인 및 세션관리, 타인의 로또 결과 확인, 
스웨거 사용, 간단한 클라이언트 화면, 서버 배포를 의식해서 만들어보았습니다.

http://158.180.76.84 에서 사용해보실 수 있습니다.

2023-11-30 03:35 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoSchedulerService.kt
> +        while (queue.isNotEmpty()) {
이후 [d9c99b9](https://github.com/BI-kotlin-in-action/Juyeol-Song-Project-Hw/pull/2/commits/d9c99b9f0cab3266cfc36ae4c7188af748537a4b) 커밋에서 for 문으로 대체하였습니다.

2023-11-30 03:38 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoSchedulerService.kt
현재 구매를 위한 회차와 조회를 위한 회차를 같은 곳에서 관리하여 로직 상 모순이 있습니다.
시간이 바뀌자마자 다음 회차 로또가 구입되게 하기 위해 현재 회차를 캡쳐하자마자 다음 회차로 증가시켰는데 이렇게 되면 클라이언트쪽에서 당첨결과가 다 나오지 않았는데도 불구하고 조회를 시도할 수 있습니다.

추후에 로또 구매를 위한 회차, 조회를 하기 위한 회차를 나누어 관리하도록 바꿔보겠습니다.

2023-11-30 06:05 UTC, konempty requested changes
크 코틀린을 쫌 치는 개발자가 되었군요 ㅋㅋㅋ
그리고 스프링도 기초는 알고계신것 같아서 좋습니다!
쪼금만 수정부탁드릴게요~!

2023-11-30 06:05 UTC, konempty commented on lotto-web/Dockerfile
> +ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILE}", "-jar","/app.jar"]
파일끝 개행을 넣어주세요~!

2023-11-30 06:05 UTC, konempty commented on lotto-web/Dockerfile
> +ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILE}", "-jar","/app.jar"]
그리고 여기 엔트리포인트에 대괄호가 있어도 되고 없어도 되는데 두개의 실행 방식이 완전 다르다는건 알고계신가요?? ㅋㅋㅋㅋ

2023-11-30 06:05 UTC, konempty commented on lotto-web/build.gradle
> +    runtimeOnly 'com.mysql:mysql-connector-j'
라이브러리의 버전을 명시해두는게 좋습니다~!

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/config/RedisConfig.kt
> +        const val COOL_DOWN_TIME = 300L
300ms로 정해진 정량적인 기준이 있을까요..?
API 수행하다 보면 300ms를 넘는 API가 나올수도 있어요

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/aspect/CoolDownAspect.kt
> + * 연속적으로 API를 호출하는 것을 방지하기 위한 Aspect
연속적으로 실행하는걸 막는 궁극적인 목표는 뭘까요??

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/config/RedisConfig.kt
> +    fun cacheManager(connectionFactory: RedisConnectionFactory?): RedisCacheManager {
RedisConnectionFactory가 null일 경우가 있을까요..?

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/config/SecurityConfig.kt
> +                    .loginProcessingUrl("/login") // 왜 있는겨?
ㅋㅋㅋㅋ 본인이 선언하고 왜 있는지 모르신가는건가요??

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/LottoController.kt
> +        return ResponseEntity(CREATED)
굳이 바디에 내릴 정보가 없다면 리턴값을 제거하고 컨트롤러 메소드에
@ResponseStatus(HttpStatus.CREATED)
를 붙혀두시면 됩니다~!

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/LottoRecordController.kt
> +    ): ResponseEntity<LottoRecordsResponse> {
ResponseEntity를 안쓰고 바로 LottoRecordsResponse를 반환해도 괜찮을것 같은데 
ResponseEntity로 한번 래핑해주는 이유가 궁금합니다!

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/UserController.kt
> +        return ResponseEntity(OK)
이경우는 바디에 내리는게 딱히 없어보이는데 HttpStatus 200 OK대신 204 NoContent가 좋을것같아요!

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/model/Lotto.kt
> +    val numbersAsString: String,
으흠 저라면 LottoNumbers객체로 가지고 있다가 DB에 저장할때 컨버터로 스트링으로 변환해서 저장할것 같아요!
예시 : https://bepoz-study-diary.tistory.com/419

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/model/ResultRecord.kt
> +    val userId: Long,
userid를 가지는것 보단 조인을 위해 엔티티 사이의 관계로 연결한다면 어떨까요??

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/model/WinningRecord.kt
> +    // DB에 영속화하는 과정에서 6개의 로또 숫자를 6개씩 따로 따로 저장하기 까다로워 문자열로 저장하였습니다. ( 구분자 ' ' )
컨버터를 사용하면 좀더 간단하게 가능합니다~!

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/exception/ResponseConstants.kt
> + * 그러면 user에게 내려가지 않아도 괜찮을 예외가 response로 내려가지 않을까? 생각하여 프로그램에서 예상하고
요 의도가 잘 이해가 안되는데 자세하게 설명가능하실까요??
유저에게 내려가지 않아도 괜찮은 에러가 어떤걸 의미할까요

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/repository/QueueWorkingCounterRepository.kt
> +    @Lock(PESSIMISTIC_WRITE)
read를 하는 쿼리인것 같은데 비관적 쓰기락으로 걸어두는 이유가 있을까요??

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoRecordService.kt
> +        lottoRecordRepository.findMaxLottoCounterByRoundAndUserId(currentRound, userId) ?: 0L
한줄짜리 메소드에 트랜잭셔널을 걸어두신 이유가 궁금합니다!

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoRecordService.kt
> +    @Transactional
여기선 트랜잭션의 레벨을 한단계 낮춰서 readonly=true라면 좋을것 같아요!

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoSchedulerService.kt
> 클라이언트쪽에서 당첨결과가 다 나오지 않았는데도 불구하고 조회를 시도할 수 있습니다.

요부분이 잘이해가 안되는데 자세하게 설명가능하실까요??

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoSchedulerService.kt
> + * 결과를 늦게 반환하거나 정말 말도 안되게 많은 요청을 받아 이후 회차에도 영향을 줄 수 있는 설계는 아닐까 고민을 했습니다.
크 현실적인 고민이네요 ㅋㅋㅋ
그런 이슈로 보통 은행이나 정부기관들은 점검시간이라는 이유로 매일 배치를 돌리는 시간에는 
어떠한 요청도 추가로 받지 않는답니다~! ㅋㅋㅋㅋ

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoSchedulerService.kt
> +    fun scheduledFunction() {
이 메소드 하는일이 많아서 동시성 이슈가 있을것 같은데
트랜잭션 처리로 해야하지 않을까요??
아마 추측하건데 이전에 언급하신 
> 클라이언트쪽에서 당첨결과가 다 나오지 않았는데도 불구하고 조회를 시도할 수 있습니다.

요 이슈가 트랜잭션이 없어서 발생하는 이유가 아닐까 싶네요 ㅋㅋㅋ

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/UserService.kt
> +    // 트랜잭션만으로 완벽하게 한 가지 값에 여러 쓰레드가
"완벽"은 없어요 ㅋㅋㅋ..
다만 대부분 방어가 가능할뿐
완벽한 동시성 제어를 위해선 쓰레드를 하나만 쓰는 방법밖에 없어요

그게 DB의 격리레벨에 관한 이야기구요

충돌은 완벽하게 피하는건 불가능하다는걸 항상 머리속에 세겨두셔야 하구요 
대신 충돌이 일어났을때 안전하게 롤백시키는 로직을 만들수 있는지 확인하는게 좋을것 같아요

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/utils/validator/LottoBuyRequestValidator.kt
> +class LottoBuyRequestValidator : ConstraintValidator<ValidLottoBuyRequest, LottoBuyRequest> {
Validator와 어노테이션은 한짝이니까 같은 파일안에 있는게 읽기 편할것 같아요!

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/resources/application-dev.yml
> +    open-in-view: false
오호 요거 의미를 알고 false로 두신걸까요??

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/resources/application-dev.yml
> +      ddl-auto: create-drop
ㅋㅋㅋㅋ 서버가 뜨고 죽을때마다 DB가 날라가겠군요

2023-11-30 06:05 UTC, konempty commented on lotto-web/src/main/resources/static/financeApi.js
> +setInterval(getBalance, 1000)
ide에 파일끝 개행 설정을 넣어주세요

2023-11-30 06:19 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/config/SecurityConfig.kt
> +                    .loginProcessingUrl("/login") // 왜 있는겨?
죄송합니다! 공부할 때 잘 몰랐던 부분은 주석으로  잠시 적어두고 나중에 공부를 했었는데 지우는 걸 깜빡했습니다!

2023-11-30 06:20 UTC, Unagi-zoso commented on lotto-web/Dockerfile
> +ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILE}", "-jar","/app.jar"]
주의하겠습니다!

2023-11-30 06:37 UTC, Unagi-zoso commented on lotto-web/Dockerfile
> +ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILE}", "-jar","/app.jar"]
잘 몰랐습니다.. 새로운 기술 사용할 땐 정말 잘 알아보고 자신의 코드라면 다른 사람이 물어봤을 때 바로 답할 정도로 공부를 해두겠습니다!

[ ]로 감쌀 경우 명령어와 패러미터들로 명령이 실행이 되며
단순히 문자열을 사용할 경우 그 문자열 자체가 실행된다고 찾아봤습니다!

2023-11-30 06:38 UTC, Unagi-zoso commented on lotto-web/build.gradle
> +    runtimeOnly 'com.mysql:mysql-connector-j'
주의하겠습니다!

2023-11-30 06:41 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/config/RedisConfig.kt
> +        const val COOL_DOWN_TIME = 300L
정량적인 기준은 없었습니다. 목적 자체는 더블 클릭 같이 짧은 순간에 의도치않게 여러 반 호출되는걸 방지하기 위해서였습니다. 

300ms의 기준은 정상적으로 API를 호출한 뒤 300ms 뒤라면 의도적인 재호출이다라고 임의적으로 제가 정했습니다.

2023-11-30 06:43 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/aspect/CoolDownAspect.kt
> + * 연속적으로 API를 호출하는 것을 방지하기 위한 Aspect
의도치 않게 더블클릭을 하는 걸 방지하고 악의적으로 여러 번 호출하는 행위를 방지하기 위해서 뒀습니다. 
더블클릭의 경우 클라이언트 페이지쪽에서 막을 수도 있었지만 클라이언트 페이지를 거치지 않고 접근하는 경우를(postman, curl명령어) 의식해서 추가해봤습니다.

2023-11-30 06:45 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/config/RedisConfig.kt
> +    fun cacheManager(connectionFactory: RedisConnectionFactory?): RedisCacheManager {
스프링에서 주입해줄테니 그런 상황은 없을 것 같네요. 
자바 코드 자료를 참고하면서 옮겨담더니 놓쳤던 것 같습니다. 주의하겠습니다. 감사합니다!

2023-11-30 06:46 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/LottoController.kt
> +        return ResponseEntity(CREATED)
그렇군요! 감사합니다!

2023-11-30 06:55 UTC, Unagi-zoso commented on lotto-web/src/main/resources/application-dev.yml
> +      ddl-auto: create-drop
요건 개발환경에서 사용된 application-dev.yml 파일이였습니다. 회차정보를 테이블에서 관리하며
 시스템이 새로 시작할 때마다 1 회차부터 시작해야했습니다. 

그래서 개발환경에선 auto-ddl을 ceeate-drop으로 설정했고 실제 서버에서 돌아가는 환경에선 none으로 설정하였습니다.

application-prod.yml이라고 제 로컬환경엔 있는데 실제 서버에서 사용되는 파일이다 보니 깃헙에 올리긴 살짝 꺼려져 올리지 않았습니다. 미리 말씀 못드려 죄송합니다!

2023-11-30 07:00 UTC, Unagi-zoso commented on lotto-web/src/main/resources/static/financeApi.js
> +setInterval(getBalance, 1000)
주의하겠습니다!

2023-11-30 07:01 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/utils/validator/LottoBuyRequestValidator.kt
> +class LottoBuyRequestValidator : ConstraintValidator<ValidLottoBuyRequest, LottoBuyRequest> {
클래스를 나누면서도 걸렸던 부분인데 알려주셔서 감사합니다!

2023-11-30 07:06 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoSchedulerService.kt
> + * 결과를 늦게 반환하거나 정말 말도 안되게 많은 요청을 받아 이후 회차에도 영향을 줄 수 있는 설계는 아닐까 고민을 했습니다.
아 이런 이유가 있었네요! 서비스를 만든다는 건 단순히 코드뿐만 아니라 문제를 제대로 정의하고 제도나 정책으로도 해결해야하는구나 생각이 드네요! 감사합니다!

2023-11-30 07:08 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/UserService.kt
> +    // 트랜잭션만으로 완벽하게 한 가지 값에 여러 쓰레드가
개인적으로 락과 트랜잭션을 공부하면서 이해 안가는 부분이 많았는데 말씀해주신 관점으로 다시 공부하면 어려웠던 부분을 좀 더 잘 이해하게 될 것 같아요. 감사합니다!

2023-11-30 07:31 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/LottoRecordController.kt
> +    ): ResponseEntity<LottoRecordsResponse> {
Status code를 직접 명시하고 싶었고 다른 controller 메소드와 시그니쳐 형태를 통일시키면 좋지 않을까 생각했습니다. 아무래도 필요없는 부분은 줄이는 게 나을까요?

2023-11-30 07:31 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/UserController.kt
> +        return ResponseEntity(OK)
그렇네요 감사합니다!

2023-11-30 07:38 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/model/ResultRecord.kt
> +    val userId: Long,
User 엔티티는 순수하게 사용자의 상태를 담당하는 클래스고 ResultRecord는 로또 당첨결과를 담당하는 조회용 엔티티 클래스입니다 .

목적이 다른 두 엔티티 사이에 참조로 접근가능하게 하는 것이 조금 관계를 복잡하게하는 기분이 들어 ResultRecord에서 userId로 조인을 해서 사용하게 하였습니다.

이런 경우 그냥 User를 참조하게 하는 편이 더 관리하기가 편할까요?

2023-12-26 12:38 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoSchedulerService.kt
현재 방식은 scheduledFunction()이 실행될 때 lottoRound를 바로 증가시킵니다.
```
val capturedCurrentRound = lottoRoundControlService.getLottoRound()
lottoRoundControlService.increaseRound()
```
이러한 이유에는 현재 회차(1회차라 가정)의 로또들의 결과를 구하기 전에 회차를 증가시켜 이후에 구매하는 로또는 다음 회차(2회차)의 로또로 구매시키기 위해서 입니다. 이후 현재 회차(1회차)는 조회가 가능해집니다.
```
LottoRoundControlService.kt

// 조회 가능한 회차를 반환한다.
    fun getAvailableRound() =
        lottoRoundControlRepository.findLottoRoundControlByLottoRoundControlId(0).round - 1
```

하지만 아직  로또 결과(1회차)가 다 처리되지도 않았는데도 조회를 가능하게 하는 것은 바람직한 서비스가 아니지 않을까 하는 생각이 들었습니다.

```
// 이번 회차의 모든 로또 구매 작업이 끝날 때까지 대기
while (queueWorkingCounterService.isNotCounterZero(capturedCurrentRound)) {}

// 이번 회차 queue 에 있는 모든 메시지를 처리
for (message in getQueueByRound(capturedCurrentRound)) {
    val lottoJob = LottoJob.from(message.message)
    resultRecordService.processResultRecords(lottoJob, winningRecordThisRound)
}
```

그렇기에 구매할 때의 회차와 조회할 때의 회차를 따로 구분하여 구매할 때의 회차는 scheduledFuncion이 시작할 때 바로 증가시키고 조회할 때의 회차는 scheduledFunction의 로직이 다 끝났을 때 마지막에 증가시켜 조회를 가능하게 만들면 좋지 않았을까? 하는 생각이였습니다.

2023-12-31 12:35 UTC, Unagi-zoso commented on lotto-web/src/main/resources/application-dev.yml
> +    open-in-view: false
DB 커넥션, 영속성 컨텍스트 반환시기를 다루는 것으로 알고 있습니다.
true(default)일 때는 controller에서 응답을 하기 직전까지 사용할 수 있지만
false일 때는 트랜잭션이 종료하기 전까지 사용할 수 있습니다.

장점으로는 DB 커넥션을 효율적으로 사용할 수 있어 트래픽이 부담될 때 도움이 될 수 있습니다.
위험성으로는 트랜잭션 범위를 넘어서는 곳에서 lazy loading을 시도할 시 영속성 컨텍스트가 반환된 뒤라 문제가 생깁니다.

현재 저의 코드에선 Lazy loading 없이 join을 통해 데이터를 바로 받아오고 있습니다. 그래서 false로 두었습니다.
트래픽이 과하지도 않았는데 너무 성급한 설정이였을까요?

혹시 제가 잘못된 정보를 알고있다면 알려주시면 정말 감사하겠습니다!

2024-01-01 09:54 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/LottoRecordController.kt
> +    ): ResponseEntity<LottoRecordsResponse> {
아뇨 요건 갠취라 ㅋㅋㅋ 뭐로 하시든 상관 없구요
제가 질문드린다고 무조건 고치라는게 아니예요 ㅋㅋㅋ 
그냥 단순한 궁금증이였어요

2024-01-01 09:57 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/model/ResultRecord.kt
> +    val userId: Long,
의도 자체는 좋았는데
그러면 한번의 결과를 조회하기 위해 2번의 쿼리를 날리게 될텐데 (결고 조회 1번, 그 결과의 유저 정보 조회 1번)
하지만 연관관계를 묶어둔다면 페치 조인 쿼리로 한번의 쿼리로도 처리가 가능해서 성능이 좋아질것 같아서 추천해드렸습니다~!
요것도 갠취라 적용안하셔도 좋은데 저는 그정도의 관계는 별로 복잡하다고 여기는 편이 아니라서 참조로 접근하는걸 선호합니다 ㅎㅎ

2024-01-01 09:58 UTC, konempty commented on lotto-web/src/main/resources/application-dev.yml
> +    open-in-view: false
어후 ㅋㅋㅋㅋ 아뇨 그냥 알고 쓴건지 궁금해서 물어본건데
고치라는 의미는 아니었구요
그런 의도라면 지금처럼 두는게 맞습니다~!

2024-01-01 10:40 UTC, konempty commented on lotto-web/src/main/resources/application-dev.yml
> +      ddl-auto: create-drop
prod파일도 올리고 비밀정보만 환경변수나 프로그램 실행파라메터로 주입한다면 좋을것 같아요~!

2024-01-01 10:41 UTC, konempty commented
ㅋㅋㅋ;;
저한테 직접적으로 멘션을 주시거나 재 리뷰요청을 주시지 않으면 저한테 알림이 오지 않습니다 ㅋㅋㅋㅋ..
다음부터는 제가 질문에 답을 안달아 준다 싶으면 @konempty 멘션을 달아주세요~!

2024-01-01 10:48 UTC, Unagi-zoso commented
> @Unagi-zoso ㅋㅋㅋ;;
> 저한테 직접적으로 멘션을 주시거나 재 리뷰요청을 주시지 않으면 저한테 알림이 오지 않습니다 ㅋㅋㅋㅋ..
> 다음부터는 제가 질문에 답을 안달아 준다 싶으면 @konempty 멘션을 달아주세요~!

제가 아직 코드를 좀 더 손 보고 있어서 아직 요청을 못 보냈습니다! 
얼마 안남았으니 다시 요청 드리겠습니다!

2024-01-01 10:49 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/aspect/CoolDownAspect.kt
> + * 연속적으로 API를 호출하는 것을 방지하기 위한 Aspect
요건 정책의 문제이긴한데
보통 빠르게 요청보내는것도 너무 심하지만 않으면 허용을 하구요
만약 중복 요청이 오면 곤란한 경우에는 막는 방법은 여러개가 있지만
그중 가장 간편한 방법은 요청에 난수를 넣어서 한개의 요청이 2번 처리되는걸 방어해요

2024-01-01 11:00 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/model/ResultRecord.kt
> +    val userId: Long,
그렇네요. 
쿼리 요청 횟수도 고려해서 결정을 해야겠어요.
 감사합니다!

2024-01-01 11:01 UTC, Unagi-zoso commented on lotto-web/src/main/resources/application-dev.yml
> +      ddl-auto: create-drop
반영하겠습니다! 감사합니다!

2024-01-05 15:42 UTC, konempty approved these changes
크 정말 고생 많이 하셨구요
아직 드릴수 있는 리뷰는 좀더 남은것 같지만
다음 기수 준비를 위해 요정도만 리뷰 드리겠습니다!
스터디 참여하시는동안 정말 고생 많이 하셨고 나중에 훌륭한 백엔드 개발자가 되면 
같이 프로젝트 한번 같이 할수 있으면 좋을것 같습니다~! 👍 👍

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/config/SecurityConfig.kt
> +        val allowedUrls = arrayOf("/login", "/loginform", "/signupform", "/api/users", "/api/users/check/username", "/swagger-ui/**")
오호 이렇게 하면 prod환경에서도 스웨거가 노출되고 익명의 사용자가 어떤 API가 있는지 모두 확인할수 있는
좋은 힌트가 되겠네요 ㅋㅋㅋ..
요건 수정할 필욘없지만 나중에 심심하면 어떻게 dev환경에서만 스웨거를 쓰도록 할지 고민하면 좋을것 같아요 :)

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/LottoController.kt
> +@RequestMapping("/api/lottos")
원래 API는 언제 버전업이 될지 모르기 때문에 Path에 API 버전을 명시해주는게 국룰입니다 ㅋㅋㅋ
ex) /api/v1/lottos

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/LottoRecordController.kt
> +@Validated
\@ Valid와 \@ Validated를 혼용하시는것 같은데 특별한 기준으로 사용처가 나뉘는 걸까요??

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/LottoJobQueuePool.kt
> +// 10분을 넘어가는 순간에도 로또를 구매할 수 있게 회차별로 queue를 미리 만들어두어 담을 수 있게 하였습니다.
이런 문제가 있다면 어떻게든 개발로 풀어내는것도 정말 좋다고 생각하는데
사실 제 최초 의도는 무조건 개발로 풀어내는게 아니라 현실과 타협해서 기획으로 풀어내서 10분 기준 앞뒤로 1분동안 로또 판매 금지!
요런걸 하는거였어요 ㅋㅋㅋ

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/LottoNumbers.kt
> +value class LottoNumbers (
아마 찾아보셨는지 모르겠는데 요 value class는 일반적인 클래스와 동작이 다르고
바이트 코드 해석방식도 특이한데 나중에 심심하면 찾아보셔도 좋을것 같아요! ㅋㅋㅋ
그걸 찾아보면 JvmInline 요 어노테이션이 왜필요 한지 자연스럽게 깨닫게 될거예요

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/LottoNumbers.kt
> +    private val numbers: SortedSet<Int>,
numbers의 크기를 따로 validation하지 않는것 같은데 내부에서 생성자가 검증을 한다면 안전한 코드가 될것 같아요!

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/LottoNumbersList.kt
> +    }
오호... 이 클래스는 너무 작아서 value클래스의 장점을 누릴수 있을지 의문이 들긴하네요 ㅋㅋㅋ...
그래도 요 코드 나쁘진 않은것 같아요~!

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/RandomLottoNumberGenerator.kt
> +         */
요건 약간 TMI이긴 한데
개발자들 사이에서는 좋은 코드는 주석이 없어도 이해하기 쉬운코드다! 라는 주장을 하는 분들이 있는데
요렇게 친절한 주석을 보면 가끔 요 주장이 떠오르는것 같아요 ㅋㅋㅋ

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/RandomLottoNumberGenerator.kt
> + */
아 그리고 저 여기서 깨달았는데 javaDoc의 형식을 잘 따르시는것 같아서 좋네요~!
하지만 요즘은 VCS가 잘되어 있고 블레임이 하기 쉬워서 요런 주석은 줄어드는 추세라고 들었어요 ㅋㅋㅋ

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/model/Lotto.kt
> +    var lottoId: Long? = null,
으흠 nullable이면 코드에서 많은 불편함이 따라올텐데 요기서 nullable을 하신 이유가 궁금하구요
제가 추측하는 이유가 맞다면 nullable을 쓰지 않고 해결이 가능할것 같은데 주열님의 문제를 해결할 더 나은 방법은 없었을까요??

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/model/LottoRecord.kt
> +    val lottoId: Long,
복합키 문제가 보통 인덱스가 키 선언 순서대로 걸린다는 건데
약간 과한 우려이긴 하지만 lottoId기준으로 DB를 검색할 니즈가 없다고 확신할수 있을까요?? ㅋㅋㅋ

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/model/LottoRoundControl.kt
> +    val lottoRoundControlId: Long = 0L,
어 여기는 id가 nullable이 아니네요..?

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/dto/LottoRecordsResponse.kt
> + * 일급 컬렉션이라고 불러도 적절한지는 모르겠습니다.
요거 좋은 패턴이예요!
갠취긴 하지만 저는 회사에서 저렇게 요청/응답을 위해 단순히 감싸는 DTO 자주 만들어요 ㅋㅋㅋ

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/repository/LottoRecordRepository.kt
> +        """,
ㄷㄷㄷㄷ
요런걸 회피하기위해 크리테리아 API나 쿼리DSL, kotlin JDSL등을 도입해보면
주열님 성장에 좋을것 같아요!

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoBuyService.kt
> +    private fun saveLottoAndRecord(
한개의 클래스가 이렇게 많은 private메소드를 가진다는건 너무 많은 역할을 수행하고 있다는건데
요걸 좀더 잘게 쪼갠다면 좋은 코드에 좀더 가까워 지지 않을까 싶네요 ㅋㅋㅋ

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoRecordService.kt
> +        lottoRecordRepository.save(
아하 ㅋㅋㅋ..
<img width="780" alt="스크린샷 2024-01-06 오전 12 33 25" src="https://github.com/BI-kotlin-in-action/Juyeol-Song-Project-Hw/assets/44064530/3076daf3-0015-4249-8a95-d1f39a17dbc4">

이전에 드렸던 리뷰가 여기에도 해당하는 질문이었는데
얘도 길어보이긴 하지만 실제론 DB에 쿼리를 한번날리는 메소드 인데
굳이 트랜잭셔널 범위안에 있어서 속도를 낮춰야 할까요..??

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/LottoRecordService.kt
> +    // lazy loading을 사용하지 않기에 조회용 메소드엔 트랜잭션을 걸지 않았습니다. @Transactional(readOnly = true)라도 거는게 좋을까요/
다른 요청의 Write연산에 의해 조회 데이터가 일부 오염되거나 불일치가 발생할수 있는걸 감수할수 있는 부분이라면
저는 지금의 상태가 훨신 낫다고 생각합니다~!
주열님이 보시기엔 요 메소드는 그정도는 감수할수 있는 메소드 인가요??

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/QueueWorkingCounterService.kt
> +import com.example.lottoweb.domain.LottoJobQueuePool.Companion.getQueueIndexByRound
ㅋㅋㅋㅋ getQueueIndexByRound 메소드가 어디있나 싶었는데 컴패니언을 통채로 임포트 하셨군요 ㅋㅋㅋ
사용할때 LottoJobQueuePool.getQueueIndexByRound 라고 사용하는게 더 읽기 좋은 코드일것 같아요

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/UserService.kt
> +    // 지금 방식처럼 여기서 생성할까요?
요건 순수하게 갠취구요
대신 한번정한 룰은 모든 코드에서 동일하게 적용되면됩니다~!

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/UserService.kt
> +    @Transactional(isolation = Isolation.READ_COMMITTED)
오호 ㅋㅋㅋ 굳이 READ_COMMITTED로 설정하신 이유가 있을까요??

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/WinningRecordService.kt
> +    fun generateNewWinningRecord(currentRound: Int): WinningRecord {
요기도 사실상 DB쿼리 한번 날라가는 메소드 같네요 ㅋㅋㅋ

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/resources/application.yml
> +    active: dev
그레이스풀 셧다운 설정도 있고 해당 설정을 위한 고려도 프로젝트에 반영된다면 더 나은 코드가 될것 같네요~!

2024-01-05 15:42 UTC, konempty commented on lotto-web/src/main/resources/templates/loginForm.html
> +</html>
와우 파일끝 개행이 빠졌네요 ㅋㅋㅋ
IDE 설정에 파일끝 개행 설정을 확인해주세요~!

2024-01-05 15:58 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/config/SecurityConfig.kt
> +        val allowedUrls = arrayOf("/login", "/loginform", "/signupform", "/api/users", "/api/users/check/username", "/swagger-ui/**")
꼭 적용해보겠습니다!

2024-01-05 15:58 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/controller/LottoController.kt
> +@RequestMapping("/api/lottos")
아하! 감사합니다!

2024-01-05 16:01 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/LottoJobQueuePool.kt
> +// 10분을 넘어가는 순간에도 로또를 구매할 수 있게 회차별로 queue를 미리 만들어두어 담을 수 있게 하였습니다.
다음에 프로젝트할 땐 그런 부분도 고려해보겠습니다.

2024-01-05 16:03 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/domain/LottoNumbers.kt
> +value class LottoNumbers (
이 부분은 꼭 바이트 코드 수준까지 깊게 공부해보겠습니다!

2024-01-05 16:06 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/repository/LottoRecordRepository.kt
> +        """,
JDSL 공부해서 꼭 도입해보겠습니다!

2024-01-05 16:08 UTC, Unagi-zoso commented on lotto-web/src/main/kotlin/com/example/lottoweb/service/QueueWorkingCounterService.kt
> +import com.example.lottoweb.domain.LottoJobQueuePool.Companion.getQueueIndexByRound
주의하겠습니다!

2024-01-05 16:10 UTC, Unagi-zoso commented on lotto-web/src/main/resources/application.yml
> +    active: dev
무지했던 부분인데 알려주셔서 감사합니다! 꼭 반영하겠습니다!

2024-01-05 16:13 UTC, Unagi-zoso commented on lotto-web/src/main/resources/templates/loginForm.html
> +</html>
매번 개행 빼먹는 일이 있으니 고개를 들 수가 없네요.. IDE로 확실하게 처리하겠습니다!

2024-01-23 17:17 UTC, merged